"use client";

import React, { useEffect, useRef, useState } from "react";
import { usePDF } from "@react-pdf/renderer";
import { toast } from "sonner";
import { CompanySettings, DocumentData } from "./pdf";
import { DynamicPdfDocument } from "./dynamic-pdf-document";
import { createPdfDocument } from "./actions";
import { Button } from "@/components/ui/button";
import { Download, Loader2, UploadCloud } from "lucide-react";
// Generated by `generateReactHelpers<OurFileRouter>()` in your existing
// UploadThing setup. If your FileRouter doesn't yet have a route for PDFs,
// add one — e.g.:
//   pdfUploader: f({ "application/pdf": { maxFileSize: "16MB" } })
//     .onUploadComplete(() => {}),
// and adjust the endpoint name below to match.
import { useUploadThing } from "@/lib/uploadthing";

/**
 * Renders the PDF as a blob URL inside a plain <iframe> instead of
 * react-pdf's <PDFViewer>. This gives us control over the PDF's own
 * "open parameters" (#view=Fit) so the browser's built-in PDF renderer
 * shows the *entire page* shrunk to fit, rather than defaulting to a
 * full-width zoom that crops the top/bottom.
 *
 * NOTE: this uses a single `usePDF` instance for both the preview and
 * the download button. Mounting `PDFDownloadLink` alongside `usePDF`
 * in the same tree creates two competing render-queues that can loop
 * forever ("Maximum update depth exceeded"), so the download link is
 * built manually from `instance.url` instead.
 */
const DEBOUNCE_MS = 400;

export const PdfPreview = React.memo(function PdfPreview({
  company,
  data,
}: {
  company: CompanySettings;
  data: DocumentData;
}) {
  // `usePDF`'s document option only seeds the *initial* render — the effect
  // inside the hook that builds the blob runs once on mount and does not
  // re-run when `company`/`data` change on later renders. The only way to
  // regenerate the PDF afterwards is to call the `update` function it
  // returns, so we do that here ourselves, debounced so we're not
  // re-rendering the PDF on every keystroke.
  const [instance, update] = usePDF({
    document: <DynamicPdfDocument company={company} document={data} />,
  });

  const isFirstRender = useRef(true);
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    if (isFirstRender.current) {
      // Skip the mount render — usePDF already built this version for us.
      isFirstRender.current = false;
      return;
    }

    if (timer.current) clearTimeout(timer.current);
    timer.current = setTimeout(() => {
      update(<DynamicPdfDocument company={company} document={data} />);
    }, DEBOUNCE_MS);

    return () => {
      if (timer.current) clearTimeout(timer.current);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [company, data]);

  const canDownload = !instance.loading && !instance.error && !!instance.url;

  // --- Save to library: upload the generated PDF, then store its metadata ---
  const [isSaving, setIsSaving] = useState(false);
  const [uploadProgress, setUploadProgress] = useState(0);

  const { startUpload } = useUploadThing("pdfUploader", {
    onUploadProgress: (progress) => setUploadProgress(progress),
  });

  async function handleSaveToLibrary() {
    if (!canDownload || !instance.blob) return;

    setIsSaving(true);
    setUploadProgress(0);

    const filename = `${data.title || "document"}.pdf`;
    const file = new File([instance.blob], filename, {
      type: "application/pdf",
    });

    const toastId = toast.loading("Uploading PDF…", { description: "0%" });

    try {
      const uploaded = await startUpload([file]);
      const url = uploaded?.[0]?.url;
      if (!url) throw new Error("Upload didn't return a file URL");

      toast.loading("Saving details…", {
        id: toastId,
        description: "Almost done",
      });

      const result = await createPdfDocument({
        filepath: url,
        filename,
        title: data.title || "Untitled document",
        client: data.client,
        tags: data.tags || [],
        companySnapshot: company,
        pages: data.pages || [[data.content || ""]],
      });

      if (!result.success) throw new Error(result.error);

      toast.success("Saved to your library", {
        id: toastId,
        description: filename,
      });
    } catch (err) {
      console.error("Failed to save PDF:", err);
      toast.error("Couldn't save the PDF", {
        id: toastId,
        description: err instanceof Error ? err.message : "Please try again.",
      });
    } finally {
      setIsSaving(false);
      setUploadProgress(0);
    }
  }

  return (
    <div className="w-full h-full flex flex-col bg-background">
      {/* Top bar */}
      <div className="flex items-center justify-between px-4 py-2.5 border-b border-border bg-card shrink-0 gap-2">
        <span className="text-sm font-medium text-muted-foreground">
          Preview
        </span>
        <div className="flex items-center gap-2">
          <Button
            type="button"
            size="sm"
            variant="outline"
            disabled={!canDownload || isSaving}
            onClick={handleSaveToLibrary}
          >
            {isSaving ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                {uploadProgress > 0 ? `${uploadProgress}%` : "Saving…"}
              </>
            ) : (
              <>
                <UploadCloud className="h-4 w-4" />
                Save to Library
              </>
            )}
          </Button>

          <Button
            type="button"
            size="sm"
            disabled={!canDownload}
            asChild={canDownload}
          >
            {canDownload ? (
              <a
                href={instance.url!}
                download={`${data.title || "document"}.pdf`}
              >
                <Download className="h-4 w-4" />
                Download PDF
              </a>
            ) : (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                Generating…
              </>
            )}
          </Button>
        </div>
      </div>

      {/* Upload progress bar */}
      {isSaving && (
        <div className="h-1 w-full bg-muted shrink-0">
          <div
            className="h-full bg-primary transition-all duration-200"
            style={{ width: `${Math.max(uploadProgress, 4)}%` }}
          />
        </div>
      )}

      {/* Preview body */}
      <div className="flex-1 min-h-0">
        {instance.loading ? (
          <div className="w-full h-full flex items-center justify-center text-sm text-muted-foreground">
            Generating preview…
          </div>
        ) : instance.error || !instance.url ? (
          <div className="w-full h-full flex items-center justify-center text-sm text-destructive">
            Couldn&apos;t render preview.
          </div>
        ) : (
          <iframe
            key={instance.url}
            src={`${instance.url}#view=Fit&toolbar=0`}
            title="PDF preview"
            className="w-full h-full border-0 bg-background"
          />
        )}
      </div>
    </div>
  );
});
