import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Stack_Sans_Notch } from "next/font/google";
import "./globals.css";
import Navbar from "@/containers/navbar";
import MobileBottomNav from "@/components/custom/mobile-bottom-nav";

const stackSansNotch = Stack_Sans_Notch({
  variable: "--font-stack-sans",
  subsets: ["latin"],
  display: "swap", // 👈 This skips fallback matching and silences the warning
});

const inter = Inter({
  variable: "--font-inter-sanserif",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${stackSansNotch.variable} h-full font-inter antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        <div>{children}</div>
        {/* <MobileBottomNav /> */}
      </body>
    </html>
  );
}
