import { ThemeProvider } from "@/providers/theme-provide";
import type { Metadata } from "next";
import { Inter, Stack_Sans_Notch } from "next/font/google";
import "./globals.css";

const stackSansNotch = Stack_Sans_Notch({
  variable: "--font-stack-sans",
  subsets: ["latin"],
  display: "swap", // 👈 This skips fallback matching and silences the warning
});

const inter = Inter({
  variable: "--font-inter-sanserif",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.variable} ${stackSansNotch.variable} h-full font-inter antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
